# Generated by Django 5.0.4 on 2024-05-01 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MultiAxisDataPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_name', models.CharField(max_length=256)),
                ('tag_value', models.IntegerField()),
                ('timestamp', models.DateTimeField()),
            ],
        ),
    ]
